
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/opt/homebrew/opt/llvm/bin/"
      - "/opt/homebrew/opt/llvm/sbin/"
      - "/opt/homebrew/opt/llvm/"
      - "/opt/homebrew/opt/protobuf/bin/"
      - "/opt/homebrew/opt/protobuf/sbin/"
      - "/opt/homebrew/opt/protobuf/"
      - "/opt/homebrew/opt/grpc/bin/"
      - "/opt/homebrew/opt/grpc/sbin/"
      - "/opt/homebrew/opt/grpc/"
      - "/opt/homebrew/opt/quantlib/bin/"
      - "/opt/homebrew/opt/quantlib/sbin/"
      - "/opt/homebrew/opt/quantlib/"
      - "/opt/homebrew/opt/apache-arrow/bin/"
      - "/opt/homebrew/opt/apache-arrow/sbin/"
      - "/opt/homebrew/opt/apache-arrow/"
      - "/opt/homebrew/opt/postgresql@17/bin/"
      - "/opt/homebrew/opt/grpc/bin/"
      - "/opt/homebrew/opt/protobuf/bin/"
      - "/opt/homebrew/opt/llvm/bin/"
      - "/opt/anaconda3/condabin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/namtran/.nvm/versions/node/v22.19.0/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/Library/Apple/usr/bin/"
    searched_directories:
      - "/opt/homebrew/opt/llvm/bin/uname"
      - "/opt/homebrew/opt/llvm/sbin/uname"
      - "/opt/homebrew/opt/llvm/uname"
      - "/opt/homebrew/opt/protobuf/bin/uname"
      - "/opt/homebrew/opt/protobuf/sbin/uname"
      - "/opt/homebrew/opt/protobuf/uname"
      - "/opt/homebrew/opt/grpc/bin/uname"
      - "/opt/homebrew/opt/grpc/sbin/uname"
      - "/opt/homebrew/opt/grpc/uname"
      - "/opt/homebrew/opt/quantlib/bin/uname"
      - "/opt/homebrew/opt/quantlib/sbin/uname"
      - "/opt/homebrew/opt/quantlib/uname"
      - "/opt/homebrew/opt/apache-arrow/bin/uname"
      - "/opt/homebrew/opt/apache-arrow/sbin/uname"
      - "/opt/homebrew/opt/apache-arrow/uname"
      - "/opt/homebrew/opt/postgresql@17/bin/uname"
      - "/opt/homebrew/opt/grpc/bin/uname"
      - "/opt/homebrew/opt/protobuf/bin/uname"
      - "/opt/homebrew/opt/llvm/bin/uname"
      - "/opt/anaconda3/condabin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/Users/namtran/.nvm/versions/node/v22.19.0/bin/uname"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{CMAKE_PREFIX_PATH}:
        - "/opt/homebrew/opt/llvm"
        - "/opt/homebrew/opt/protobuf"
        - "/opt/homebrew/opt/grpc"
        - "/opt/homebrew/opt/quantlib"
        - "/opt/homebrew/opt/apache-arrow"
      ENV{PATH}:
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/opt/homebrew/opt/grpc/bin"
        - "/opt/homebrew/opt/protobuf/bin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/opt/homebrew/opt/grpc/bin"
        - "/opt/homebrew/opt/protobuf/bin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/opt/anaconda3/condabin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/namtran/.nvm/versions/node/v22.19.0/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:218 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.3.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:66 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/opt/homebrew/opt/llvm/bin/"
      - "/opt/homebrew/opt/llvm/sbin/"
      - "/opt/homebrew/opt/llvm/"
      - "/opt/homebrew/opt/protobuf/bin/"
      - "/opt/homebrew/opt/protobuf/sbin/"
      - "/opt/homebrew/opt/protobuf/"
      - "/opt/homebrew/opt/grpc/bin/"
      - "/opt/homebrew/opt/grpc/sbin/"
      - "/opt/homebrew/opt/grpc/"
      - "/opt/homebrew/opt/quantlib/bin/"
      - "/opt/homebrew/opt/quantlib/sbin/"
      - "/opt/homebrew/opt/quantlib/"
      - "/opt/homebrew/opt/apache-arrow/bin/"
      - "/opt/homebrew/opt/apache-arrow/sbin/"
      - "/opt/homebrew/opt/apache-arrow/"
      - "/opt/homebrew/opt/postgresql@17/bin/"
      - "/opt/homebrew/opt/grpc/bin/"
      - "/opt/homebrew/opt/protobuf/bin/"
      - "/opt/homebrew/opt/llvm/bin/"
      - "/opt/anaconda3/condabin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/namtran/.nvm/versions/node/v22.19.0/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/Library/Apple/usr/bin/"
    searched_directories:
      - "/opt/homebrew/opt/llvm/bin/install_name_tool"
      - "/opt/homebrew/opt/llvm/sbin/install_name_tool"
      - "/opt/homebrew/opt/llvm/install_name_tool"
      - "/opt/homebrew/opt/protobuf/bin/install_name_tool"
      - "/opt/homebrew/opt/protobuf/sbin/install_name_tool"
      - "/opt/homebrew/opt/protobuf/install_name_tool"
      - "/opt/homebrew/opt/grpc/bin/install_name_tool"
      - "/opt/homebrew/opt/grpc/sbin/install_name_tool"
      - "/opt/homebrew/opt/grpc/install_name_tool"
      - "/opt/homebrew/opt/quantlib/bin/install_name_tool"
      - "/opt/homebrew/opt/quantlib/sbin/install_name_tool"
      - "/opt/homebrew/opt/quantlib/install_name_tool"
      - "/opt/homebrew/opt/apache-arrow/bin/install_name_tool"
      - "/opt/homebrew/opt/apache-arrow/sbin/install_name_tool"
      - "/opt/homebrew/opt/apache-arrow/install_name_tool"
      - "/opt/homebrew/opt/postgresql@17/bin/install_name_tool"
      - "/opt/homebrew/opt/grpc/bin/install_name_tool"
      - "/opt/homebrew/opt/protobuf/bin/install_name_tool"
      - "/opt/homebrew/opt/llvm/bin/install_name_tool"
      - "/opt/anaconda3/condabin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/Users/namtran/.nvm/versions/node/v22.19.0/bin/install_name_tool"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{CMAKE_PREFIX_PATH}:
        - "/opt/homebrew/opt/llvm"
        - "/opt/homebrew/opt/protobuf"
        - "/opt/homebrew/opt/grpc"
        - "/opt/homebrew/opt/quantlib"
        - "/opt/homebrew/opt/apache-arrow"
      ENV{PATH}:
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/opt/homebrew/opt/grpc/bin"
        - "/opt/homebrew/opt/protobuf/bin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/opt/homebrew/opt/grpc/bin"
        - "/opt/homebrew/opt/protobuf/bin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/opt/anaconda3/condabin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/namtran/.nvm/versions/node/v22.19.0/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
